const mostPopularPosts = {
  javascript: [
    {
      title: "1. JavaScript Lodash Fundamentals",
      image: "/picture1.png",
      description: "This is a short post description",
      tags: ["javascript", "lodash", "array"],
      content: "This is the long long long post content",
      createdAt: "Jan 21, 2021",
    },
    {
      title: "2. JavaScript Lodash Fundamentals",
      image: "/picture1.png",
      description: "This is a short post description",
      tags: ["javascript", "node.js"],
      content: "This is the long long long post content",
      createdAt: "Jan 21, 2021",
    },
    {
      title: "3. JavaScript Lodash Fundamentals",
      image: "/picture1.png",
      description: "This is a short post description",
      tags: ["browser", "lodash"],
      content: "This is the long long long post content",
      createdAt: "Jan 21, 2021",
    },
    {
      title: "4. JavaScript Lodash Fundamentals",
      image: "/picture1.png",
      description: "This is a short post description",
      tags: ["async", "react"],
      content: "This is the long long long post content",
      createdAt: "Jan 21, 2021",
    },
    {
      title: "5. JavaScript Lodash Fundamentals",
      image: "/picture1.png",
      description: "This is a short post description",
      tags: ["javascript", "lodash"],
      content: "This is the long long long post content",
      createdAt: "Jan 21, 2021",
    },
    {
      title: "6. JavaScript Lodash Advanced Concepts",
      image: "/picture1.png",
      description: "This is a short post description",
      tags: ["javascript", "lodash"],
      content: "This is the long long long post content",
      createdAt: "Jan 21, 2021",
    },
    {
      title: "7. JavaScript Lodash Examples",
      image: "/picture1.png",
      description: "This is a short post description",
      tags: ["javascript", "lodash"],
      content: "This is the long long long post content",
      createdAt: "Jan 21, 2021",
    },
  ],
  algorithms: [
    {
      title: "1. Algorithms Lodash Fundamentals",
      image: "/picture1.png",
      description: "This is a short post description",
      tags: ["algorithm", "O-notation"],
      content: "This is the long long long post content",
      createdAt: "Jan 21, 2021",
    },
    {
      title: "2. Algorithms Lodash Advanced Concepts",
      image: "/picture1.png",
      description: "This is a short post description",
      tags: ["list", "linkedList"],
      content: "This is the long long long post content",
      createdAt: "Jan 21, 2021",
    },
    {
      title: "3. Algorithms Lodash Examples",
      image: "/picture1.png",
      description: "This is a short post description",
      tags: ["graph", "cycle"],
      content: "This is the long long long post content",
      createdAt: "Jan 21, 2021",
    },
    {
      title: "4. Algorithms Lodash Fundamentals",
      image: "/picture1.png",
      description: "This is a short post description",
      tags: ["binary-tree", "tree"],
      content: "This is the long long long post content",
      createdAt: "Jan 21, 2021",
    },
    {
      title: "5. Algorithms Lodash Advanced Concepts",
      image: "/picture1.png",
      description: "This is a short post description",
      tags: ["javascript", "lodash"],
      content: "This is the long long long post content",
      createdAt: "Jan 21, 2021",
    },
    {
      title: "6. Algorithms Lodash Examples",
      image: "/picture1.png",
      description: "This is a short post description",
      tags: ["javascript", "lodash"],
      content: "This is the long long long post content",
      createdAt: "Jan 21, 2021",
    },
  ],
  uncategorized: [
    {
      title: "Uncategorized Lodash Fundamentals",
      image: "/picture1.png",
      description: "This is a short post description",
      tags: ["javascript", "lodash"],
      content: "This is the long long long post content",
      createdAt: "Jan 21, 2021",
    },
    {
      title: "Uncategorized Lodash Advanced Concepts",
      image: "/picture1.png",
      description: "This is a short post description",
      tags: ["javascript", "lodash"],
      content: "This is the long long long post content",
      createdAt: "Jan 21, 2021",
    },
    {
      title: "Uncategorized Lodash Examples",
      image: "/picture1.png",
      description: "This is a short post description",
      tags: ["javascript", "lodash"],
      content: "This is the long long long post content",
      createdAt: "Jan 21, 2021",
    },
  ],
};


const allPosts = {
  javascript: [
    {
      title: "All Posts: JavaScript Lodash Fundamentals",
      image: "/picture1.png",
      description: "This is a short post description",
      tags: ["javascript", "lodash"],
      content: "This is the long long long post content",
      createdAt: "Jan 21, 2021",
    },
    {
      title: "All Posts: JavaScript Lodash Advanced Concepts",
      image: "/picture1.png",
      description: "This is a short post description",
      tags: ["javascript", "lodash"],
      content: "This is the long long long post content",
      createdAt: "Jan 21, 2021",
    },
    {
      title: "All Posts: JavaScript Lodash Examples",
      image: "/picture1.png",
      description: "This is a short post description",
      tags: ["javascript", "lodash"],
      content: "This is the long long long post content",
      createdAt: "Jan 21, 2021",
    },
  ],
  algorithms: [
    {
      title: "All Posts: Algorithms Lodash Fundamentals",
      image: "/picture1.png",
      description: "This is a short post description",
      tags: ["javascript", "lodash"],
      content: "This is the long long long post content",
      createdAt: "Jan 21, 2021",
    },
    {
      title: "All Posts: Algorithms Lodash Advanced Concepts",
      image: "/picture1.png",
      description: "This is a short post description",
      tags: ["javascript", "lodash"],
      content: "This is the long long long post content",
      createdAt: "Jan 21, 2021",
    },
    {
      title: "All Posts: Algorithms Lodash Examples",
      image: "/picture1.png",
      description: "This is a short post description",
      tags: ["javascript", "lodash"],
      content: "This is the long long long post content",
      createdAt: "Jan 21, 2021",
    },
  ],
  uncategorized: [
    {
      title: "All Posts: Uncategorized Lodash Fundamentals",
      image: "/picture1.png",
      description: "This is a short post description",
      tags: ["javascript", "lodash"],
      content: "This is the long long long post content",
      createdAt: "Jan 21, 2021",
    },
    {
      title: "All Posts: Uncategorized Lodash Advanced Concepts",
      image: "/picture1.png",
      description: "This is a short post description",
      tags: ["javascript", "lodash"],
      content: "This is the long long long post content",
      createdAt: "Jan 21, 2021",
    },
    {
      title: "All Posts: Uncategorized Lodash Examples",
      image: "/picture1.png",
      description: "This is a short post description",
      tags: ["javascript", "lodash"],
      content: "This is the long long long post content",
      createdAt: "Jan 21, 2021",
    },
  ],
};

module.exports = {
    mostPopularPosts,
    allPosts
}