const allPosts = {
  javascript: [
    {
      title: "1. JavaScript Lodash Fundamentals",
      image: "/picture1.png",
      description: "This is a short post description",
      tags: ["javascript", "array"],
      content: "This is the long long long post content",
      createdAt: "Jan 21, 2021",
    },
    {
      title: "2. JavaScript Lodash Fundamentals",
      image: "/picture1.png",
      description: "This is a short post description",
      tags: ["javascript", "variable", "node.js"],
      content: "This is the long long long post content",
      createdAt: "Jan 21, 2021",
    },
    {
      title: "3. JavaScript Lodash Fundamentals",
      image: "/picture1.png",
      description: "This is a short post description",
      tags: ["browser", "lodash", "variable"],
      content: "This is the long long long post content",
      createdAt: "Jan 21, 2021",
    },
    {
      title: "4. JavaScript Lodash Fundamentals",
      image: "/picture1.png",
      description: "This is a short post description",
      tags: ["async", "react", "promise"],
      content: "This is the long long long post content",
      createdAt: "Jan 21, 2021",
    },
    {
      title: "5. JavaScript Lodash Fundamentals",
      image: "/picture1.png",
      description: "This is a short post description",
      tags: ["javascript", "lodash", "promise"],
      content: "This is the long long long post content",
      createdAt: "Jan 21, 2021",
    },
    {
      title: "6. JavaScript Lodash Advanced Concepts",
      image: "/picture1.png",
      description: "This is a short post description",
      tags: ["javascript", "lodash", "react"],
      content: "This is the long long long post content",
      createdAt: "Jan 21, 2021",
    },
    {
      title: "7. JavaScript Lodash Examples",
      image: "/picture1.png",
      description: "This is a short post description",
      tags: ["javascript", "async"],
      content: "This is the long long long post content",
      createdAt: "Jan 21, 2021",
    },
  ],
  algorithms: [
    {
      title: "1. Algorithms Lodash Fundamentals",
      image: "/picture1.png",
      description: "This is a short post description",
      tags: ["algorithm", "O-notation"],
      content: "This is the long long long post content",
      createdAt: "Jan 21, 2021",
    },
    {
      title: "2. Algorithms Lodash Advanced Concepts",
      image: "/picture1.png",
      description: "This is a short post description",
      tags: ["list", "linkedList"],
      content: "This is the long long long post content",
      createdAt: "Jan 21, 2021",
    },
    {
      title: "3. Algorithms Lodash Examples",
      image: "/picture1.png",
      description: "This is a short post description",
      tags: ["graph", "cycle", "algorithm"],
      content: "This is the long long long post content",
      createdAt: "Jan 21, 2021",
    },
    {
      title: "4. Algorithms Lodash Fundamentals",
      image: "/picture1.png",
      description: "This is a short post description",
      tags: ["binary-tree", "tree", "algorithm"],
      content: "This is the long long long post content",
      createdAt: "Jan 21, 2021",
    },
    {
      title: "5. Algorithms Lodash Advanced Concepts",
      image: "/picture1.png",
      description: "This is a short post description",
      tags: ["javascript", "algorithm"],
      content: "This is the long long long post content",
      createdAt: "Jan 21, 2021",
    },
    {
      title: "6. Algorithms Lodash Examples",
      image: "/picture1.png",
      description: "This is a short post description",
      tags: ["javascript", "lodash"],
      content: "This is the long long long post content",
      createdAt: "Jan 21, 2021",
    },
  ],
  uncategorized: [
    {
      title: "Uncategorized Lodash Fundamentals",
      image: "/picture1.png",
      description: "This is a short post description",
      tags: ["javascript", "lodash"],
      content: "This is the long long long post content",
      createdAt: "Jan 21, 2021",
    },
    {
      title: "Uncategorized Lodash Advanced Concepts",
      image: "/picture1.png",
      description: "This is a short post description",
      tags: ["javascript", "lodash"],
      content: "This is the long long long post content",
      createdAt: "Jan 21, 2021",
    },
    {
      title: "Uncategorized Lodash Examples",
      image: "/picture1.png",
      description: "This is a short post description",
      tags: ["javascript", "lodash"],
      content: "This is the long long long post content",
      createdAt: "Jan 21, 2021",
    },
    {
      title: "All Posts: JavaScript Lodash Fundamentals",
      image: "/picture1.png",
      description: "This is a short post description",
      tags: ["javascript", "lodash"],
      content: "This is the long long long post content",
      createdAt: "November 21, 2021",
    },
    {
      title: "All Posts: JavaScript Lodash Advanced Concepts",
      image: "/picture1.png",
      description: "This is a short post description",
      tags: ["javascript", "lodash"],
      content: "This is the long long long post content",
      createdAt: "October 19, 2021",
    },
    {
      title: "All Posts: JavaScript Lodash Examples",
      image: "/picture1.png",
      description: "This is a short post description",
      tags: ["javascript", "lodash"],
      content: "This is the long long long post content",
      createdAt: "June 30, 2021",
    },
    {
      title: "All Posts: JavaScript Lodash Fundamentals",
      image: "/picture1.png",
      description: "This is a short post description",
      tags: ["javascript", "lodash"],
      content: "This is the long long long post content",
      createdAt: "July 21, 2021",
    },
    {
      title: "All Posts: JavaScript Lodash Advanced Concepts",
      image: "/picture1.png",
      description: "This is a short post description",
      tags: ["javascript", "lodash"],
      content: "This is the long long long post content",
      createdAt: "July 19, 2021",
    },
    {
      title: "All Posts: JavaScript Lodash Examples",
      image: "/picture1.png",
      description: "This is a short post description",
      tags: ["javascript", "lodash"],
      content: "This is the long long long post content",
      createdAt: "July 30, 2021",
    },
    {
      title: "All Posts: Algorithms Lodash Fundamentals",
      image: "/picture1.png",
      description: "This is a short post description",
      tags: ["javascript", "lodash"],
      content: "This is the long long long post content",
      createdAt: "January 21, 2019",
    },
    {
      title: "All Posts: Algorithms Lodash Advanced Concepts",
      image: "/picture1.png",
      description: "This is a short post description",
      tags: ["javascript", "lodash"],
      content: "This is the long long long post content",
      createdAt: "April 03, 2021",
    },
    {
      title: "All Posts: Algorithms Lodash Examples",
      image: "/picture1.png",
      description: "This is a short post description",
      tags: ["javascript", "lodash"],
      content: "This is the long long long post content",
      createdAt: "September 21, 2019",
    },
    {
      title: "All Posts: Uncategorized Lodash Fundamentals",
      image: "/picture1.png",
      description: "This is a short post description",
      tags: ["javascript", "lodash"],
      content: "This is the long long long post content",
      createdAt: "March 21, 2019",
    },
    {
      title: "Recently Introduced Uncategorized Lodash Examples",
      image: "/picture1.png",
      description: "This is a short post description",
      tags: ["javascript", "lodash"],
      content: "This is the long long long post content",
      createdAt: "December 01, 2021",
    },
    {
      title: "All Posts: Uncategorized Lodash Advanced Concepts",
      image: "/picture1.png",
      description: "This is a short post description",
      tags: ["javascript", "lodash"],
      content: "This is the long long long post content",
      createdAt: "March 15, 2019",
    },
    {
      title: "All Posts: Uncategorized Lodash Examples",
      image: "/picture1.png",
      description: "This is a short post description",
      tags: ["javascript", "lodash"],
      content: "This is the long long long post content",
      createdAt: "May 21, 2021",
    },
  ],
};

module.exports = {
    allPosts,
}